//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassMW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNot
    {
        public int ID { get; set; }
        public string NotAdi { get; set; }
        public string SifreliNot { get; set; }
        public int UserID { get; set; }
    
        public virtual tblUye tblUye { get; set; }
    }
}
