//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassMW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUye()
        {
            this.tbl_Acc = new HashSet<tbl_Acc>();
            this.tblNot = new HashSet<tblNot>();
        }
    
        public int ID { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string passwordHint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Acc> tbl_Acc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNot> tblNot { get; set; }
    }
}
